# Install dependencies only when needed
FROM node:16-alpine 

# ENV NODE_ENV=production
ENV CI=true
#Next we create a directory to hold the application code inside the image
WORKDIR /app
# Install dependencies based on the preferred package manager
COPY ["package.json", "yarn.lock*", "pnpm-lock.yaml*", "./"]

# RUN yarn install --production=true
RUN yarn install
#To bundle your app's source code inside the Docker image, use the COPY instruction:
# COPY . .

FROM node:16-alpine 
WORKDIR /app
COPY --from=0 /app .
COPY . .
RUN yarn build
ENV MONGO_URL=mongodb+srv://admin:admin@sortlog-dev.tz5kdhn.mongodb.net/sortlog-dev
ENV auth_encryption_salt=some-salt
ENV PORT=4000

CMD ["yarn", "start"]



# Install dependencies only when needed
# FROM node:16-alpine 
# #Next we create a directory to hold the application code inside the image
# WORKDIR /app
# # Install dependencies based on the preferred package manager
# COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./


# RUN yarn install
# #To bundle your app's source code inside the Docker image, use the COPY instruction:
# COPY . .
# # should I have yarn build at this stagge ?

# RUN ls -a

# CMD ["node", "dist/server.js"]
