FROM node:16-alpine as node

FROM docker 

VOLUME /var/run/docker.sock /var/run/docker.sock

COPY --from=node /usr/lib /usr/lib
COPY --from=node /usr/local/share /usr/local/share
COPY --from=node /usr/local/lib /usr/local/lib
COPY --from=node /usr/local/include /usr/local/include
COPY --from=node /usr/local/bin /usr/local/bin

RUN apk add --no-cache aws-cli

EXPOSE 8090
