FROM node:16-alpine 

# ENV NODE_ENV=production
ENV CI=true
#Next we create a directory to hold the application code inside the image
WORKDIR /app

COPY . .
RUN yarn install && yarn build
ENV MONGO_URL=mongodb+srv://admin:admin@sortlog-dev.tz5kdhn.mongodb.net/sortlog-dev
ENV auth_encryption_salt=some-salt
ENV PORT=3995

CMD ["yarn", "start"]